# PY_VER=3.9 IMAGE=djtest DISTRO=alpine HOST_UID=$(id -u) docker-compose -f docker-compose-docs.yaml up --exit-code-from pharus-docs --build
#
# Used to build documentation artifacts.
version: "2.4"
services:
  pharus-docs:
    image: datajoint/${IMAGE}:py${PY_VER}-${DISTRO}
    user: ${HOST_UID}:anaconda
    volumes:
      - .:/main
      - ./requirements_docs.txt:/tmp/pip_requirements.txt
    command:
      - sh
      - -lc
      - |
        set -e
        cd docs
        echo "make" > "$$APK_REQUIREMENTS"
        /entrypoint.sh echo done.
        rm "$$APK_REQUIREMENTS"
        make html
