# PY_VER=3.8 IMAGE=djtest DISTRO=alpine HOST_UID=$(id -u) docker-compose -f docker-compose-docs-build.yaml up --exit-code-from pharus-docs --build
#
# Used to build documentation artifacts.
version: "2.4"
services:
  pharus-docs:
    image: datajoint/${IMAGE}:py${PY_VER}-${DISTRO}
    user: ${HOST_UID}:anaconda
    volumes:
      - .:/main
    command:
      - sh
      - -lc
      - |
        set -e
        cd docs
        echo "make" > "$$APK_REQUIREMENTS"
        echo "flask pyjwt[crypto] datajoint==0.13.dev4 pytest Sphinx sphinx_rtd_theme" | tr " " "\n" > "$$PIP_REQUIREMENTS"
        /entrypoint.sh echo done.
        rm "$$APK_REQUIREMENTS"
        rm "$$PIP_REQUIREMENTS"
        make html
